from setuptools import find_packages, setup

setup(
    name="biomassrecovery",
    version="0.0.3",
    author="Simon V. Mathis (AI4ER CDT, University of Cambridge)",
    author_email="author@example.com",
    description="A short description of the project.",
    url="url-to-github-page",
    packages=find_packages(),
    test_suite="src.tests.test_all.suite",
    install_requires=[
        "geoalchemy2",
        "geopandas",
        "h5py",
        "hvplot",
        "numpy",
        "pandas",
        "psutil",
        "psycopg2",
        "pyarrow",
        "pylr2",
        "pyproj",
        "pyspark",
        "python-dotenv",
        "requests",
        "rioxarray",
        "shapely",
        "sqlalchemy",
        "statsmodels",
        "tqdm",
        "utm",
        "xarray",
        "urllib3<2.0",
    ]
)
